Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/urls.py
from django.urls import path
from AppPreEntreg3 import views
from django.contrib.auth.views import LogoutView #Logout.

urlpatterns = [
    path('', views.inicio, name="Inicio"),
    path('login',views.login_request, name="Login"),
    path('register', views.register, name='Register'),
    path('logout', LogoutView.as_view(template_name='AppPreEntreg3/inicio.html'), name = 'Logout'),
    path('aboutMe', views.aboutme, name="Aboutme"),  
    path('remeras', views.remeras, name="Remeras"),
    path('buzos', views.buzos, name="Buzos"),
    path('pantalones', views.pantalones, name="Pantalones"),
    path('remerasForm', views.remerasForm, name="remerasForm"),
    path('buzosForm', views.buzosForm, name="buzosForm"),
    path('pantalonesForm', views.pantalonesForm, name="pantalonesForm"),
    path('busquedaRemera',views.busquedaRemera,name="BusquedaRemera"),
    path('buscarRem/',views.buscarRem),
    path('busquedaBuzo',views.busquedaBuzo,name="BusquedaBuzo"),
    path('buscarBuzo/',views.buscarBuzo),
    path('busquedaPantalon',views.busquedaPantalon,name="BusquedaPantalon"),
    path('buscarPant/',views.buscarPant),
    path('editarRem/<remera_nombre>/', views.editarRem, name="EditarRemera"),
    path('editarBuzo/<buzo_nombre>/', views.editarBuzo, name="EditarBuzo"),
    path('editarPant/<pantalon_nombre>/', views.editarPant, name="EditarPantalon"),
    path('eliminarRem/<remera_nombre>/', views.eliminarRem, name="EliminarRemera"),
    path('eliminarBuzo/<buzo_nombre>/', views.eliminarBuzo, name="EliminarBuzo"),
    path('eliminarPant/<pantalon_nombre>/', views.eliminarPant, name="EliminarPantalon"),
    path('editarPerfil', views.editarPerfil, name="EditarPerfil"), 
    path('agregarAvatar', views.agregarAvatar, name="AgregarAvatar"),
]

Proyecto Final/ProyectoPreEntreg3/ProyectoPreEntreg3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppPreEntreg3.urls')),
]

#Imagenes:
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

CARGO = "CA"
ELASTIZADO = "EL"
MOM = "MO"
WIDELEG = "WL" 
choicesPant = [
        (CARGO, "Cargo"),
        (ELASTIZADO, "Elastizado"),
        (MOM, "Mom"),
        (WIDELEG, "Wideleg"),]

class ProdRemera (models.Model):
    nombre = models.CharField(max_length=30)
    tamaño = models.CharField(max_length=3)
    color = models.CharField(max_length=10)
    precio = models.FloatField()
    stock = models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.nombre} - Tamaño {self.tamaño} - Color {self.color} - Precio {self.precio} - Stock {self.stock}"

class ProdBuzo (models.Model):
    nombre = models.CharField(max_length=30)
    tamaño = models.CharField(max_length=3)
    color = models.CharField(max_length=10)
    precio = models.FloatField()
    stock = models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.nombre} - Tamaño {self.tamaño} - Color {self.color} - Precio {self.precio} - Stock {self.stock}"

class ProdPantalon (models.Model):
    nombre = models.CharField(max_length=30)
    tamaño = models.CharField(max_length=3)
    color = models.CharField(max_length=10)
    diseño = models.CharField(max_length=20, choices=choicesPant, default=CARGO)
    precio = models.FloatField()
    stock = models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.nombre} - Tamaño {self.tamaño} - Color {self.color} - Precio {self.precio} - Stock {self.stock}"

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #Referencia a la estructura que almacena el usuario. El avatar se elimina junto al usuario.
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
    
    def __str__(self):
        return f"{self.user} - {self.imagen}"

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/forms.py
from django import forms
from AppPreEntreg3.models import choicesPant
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RemerasForm(forms.Form):
    id= forms.IntegerField()
    nombre= forms.CharField(max_length=30)
    tamaño = forms.CharField(max_length=3)
    color = forms.CharField(max_length=10)
    precio = forms.FloatField()
    stock = forms.IntegerField()

class BuzosForm(forms.Form):
    id= forms.IntegerField()
    nombre= forms.CharField(max_length=30)
    tamaño = forms.CharField(max_length=3)
    color = forms.CharField(max_length=10)
    precio = forms.FloatField()
    stock = forms.IntegerField()

class PantalonesForm(forms.Form):
    id= forms.IntegerField()
    nombre= forms.CharField(max_length=30)
    tamaño = forms.CharField(max_length=3)
    color = forms.CharField(max_length=10)
    diseño = forms.ChoiceField(choices=choicesPant)
    precio = forms.FloatField()
    stock = forms.IntegerField()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        # Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}

class UserEditForm(UserCreationForm):
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repetir la contraseña', widget=forms.PasswordInput)
    last_name = forms.CharField()
    first_name = forms.CharField()
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'last_name', 'first_name']

class AvatarFormulario(forms.Form):
    imagen = forms.ImageField(required=True)  #Subimos un avatar como usuario.

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden
from AppPreEntreg3.models import ProdRemera, ProdBuzo, ProdPantalon, Avatar, User
from AppPreEntreg3.forms import RemerasForm, BuzosForm, PantalonesForm, UserRegisterForm, UserEditForm, AvatarFormulario
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.hashers import make_password

def superadmin_required(view_func):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_superuser:
            return render(request, "AppPreEntreg3/inicio.html", {"mensaje5":"No eres superadmin, por favor logueate como tal"})
        return view_func(request, *args, **kwargs)
    return wrapper

# Create your views here.

def inicio(request):
    return render(request, 'AppPreEntreg3/inicio.html')

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():  # Si pasó la validación de Django
            usuario = form.cleaned_data.get('username')
            contraseña = form.cleaned_data.get('password')
            user = authenticate(username= usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "AppPreEntreg3/inicio.html", {"mensaje":f"Bienvenido {usuario}"})
            else:
                return render(request, "App1/inicio.html", {"mensaje":"Datos incorrectos"})
        else:
            return render(request, "AppPreEntreg3/login.html", {"mensaje":"Usuario o Contraseña Incorrectos", "form": form})
    form = AuthenticationForm()
    return render(request, "AppPreEntreg3/login.html", {"form": form})

def register(request):
      if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                  username = form.cleaned_data['username']
                  form.save()
                  return render(request,"AppPreEntreg3/inicio.html" ,  {"mensaje":"Usuario Creado, por favor inicie sesión"})
      else:   
            form = UserRegisterForm()     
      return render(request,"AppPreEntreg3/registro.html" ,  {"form":form})

def aboutme(request):
    return render(request, 'AppPreEntreg3/aboutme.html')

@login_required
def remeras(request):
    remeras = ProdRemera.objects.all() # trae todas las remeras.
    contexto= {"remeras": remeras}
    return render(request, 'AppPreEntreg3/remeras.html', contexto)

@login_required
def buzos(request):
    buzos = ProdBuzo.objects.all() # trae todos los buzos.
    contexto= {"buzos": buzos}
    return render(request, 'AppPreEntreg3/buzos.html', contexto)

@login_required
def pantalones(request):
    pantalones = ProdPantalon.objects.all() # trae todos los pantalones.
    contexto= {"pantalones": pantalones}
    return render(request, 'AppPreEntreg3/pantalones.html', contexto)

@login_required
def busquedaRemera(request):
     return render(request,'AppPreEntreg3/busquedaRemera.html')

@login_required
def busquedaBuzo(request):
     return render(request,'AppPreEntreg3/busquedaBuzo.html')

@login_required
def busquedaPantalon(request):
     return render(request,'AppPreEntreg3/busquedaPantalon.html')

@login_required
@superadmin_required
def remerasForm(request):
    if request.method == "POST":
        miFormulario = RemerasForm(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            remeras = ProdRemera(int(informacion['id']),str(informacion['nombre']),str(informacion['tamaño']), 
                                 informacion['color'], float(informacion['precio']), int(informacion['stock']))
            remeras.save()
            return render(request, "AppPreEntreg3/inicio.html")
    else:
        miFormulario = RemerasForm() #Formulario vacío.
             
    return render(request, "AppPreEntreg3/remerasForm.html", {"miFormulario": miFormulario})

@login_required
@superadmin_required
def buzosForm(request):
    if request.method == "POST":
        miFormulario = BuzosForm(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            buzos = ProdBuzo(int(informacion['id']),str(informacion['nombre']),str(informacion['tamaño']), 
                                 informacion['color'], float(informacion['precio']), int(informacion['stock']))
            buzos.save()
            return render(request, "AppPreEntreg3/inicio.html")
    else:
        miFormulario = BuzosForm() #Formulario vacío.
             
    return render(request, "AppPreEntreg3/buzosForm.html", {"miFormulario": miFormulario})

@login_required
@superadmin_required
def pantalonesForm(request):
    if request.method == "POST":
        miFormulario = PantalonesForm(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            pantalones = ProdPantalon(int(informacion['id']),str(informacion['nombre']),str(informacion['tamaño']), 
                                 informacion['color'], informacion['diseño'], float(informacion['precio']), int(informacion['stock']))
            pantalones.save()
            return render(request, "AppPreEntreg3/inicio.html")
    else:
        miFormulario = PantalonesForm() #Formulario vacío.
             
    return render(request, "AppPreEntreg3/pantalonesForm.html", {"miFormulario": miFormulario})

@login_required
def buscarRem(request):
    if request.GET['remera']:
        remera = request.GET['remera']
        remeras = ProdRemera.objects.filter(nombre__icontains=remera)

        return render(request,'AppPreEntreg3/resultadosRemeras.html', {"remeras":remeras, "remera": remera })
    else:
        respuesta= "No enviaste datos"

    return render(request,"AppPreEntreg3/inicio.html",{"respuesta":respuesta})

@login_required
def buscarBuzo(request):
    if request.GET['buzo']:
        buzo = request.GET['buzo']
        buzos = ProdBuzo.objects.filter(nombre__icontains=buzo)

        return render(request,'AppPreEntreg3/resultadosBuzos.html', {"buzos":buzos, "buzo": buzo })
    else:
        respuesta= "No enviaste datos"

    return render(request,"AppPreEntreg3/inicio.html",{"respuesta":respuesta})

@login_required
def buscarPant(request):
    if request.GET['pantalon']:
        pantalon = request.GET['pantalon']
        pantalones = ProdPantalon.objects.filter(nombre__icontains=pantalon)

        return render(request,'AppPreEntreg3/resultadosPantalones.html', {"pantalones":pantalones, "pantalon": pantalon })
    else:
        respuesta= "No enviaste datos"

    return render(request,"AppPreEntreg3/inicio.html",{"respuesta":respuesta})

@login_required
@superadmin_required
def editarRem(request, remera_nombre):
    remera = ProdRemera.objects.get(nombre=remera_nombre)
    # Si es metodo POST...
    if request.method == 'POST':
        miFormulario = RemerasForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid:  # Si pasó la validación de Django
            informacion = miFormulario.cleaned_data

            remera.nombre = informacion['nombre']
            remera.tamaño = informacion['tamaño']
            remera.color = informacion['color']
            remera.precio = informacion['precio']
            remera.stock = informacion['stock']
            remera.save()

            # Vuelvo al inicio.
            return render(request, "AppPreEntreg3/inicio.html")
    # En caso que no sea post...
    else:
        # Creo el formulario con los datos que voy a modificar
        miFormulario = RemerasForm(initial={'nombre': remera.nombre, 'tamaño': remera.tamaño,
                                                'color': remera.color, 'precio': remera.precio, 'stock': remera.stock})
    # Voy al html que me permite editar
    return render(request, "AppPreEntreg3/editarRemera.html", {"miFormulario": miFormulario, "remera_nombre": remera_nombre})

@login_required
@superadmin_required
def editarBuzo(request, buzo_nombre):
    buzo = ProdBuzo.objects.get(nombre=buzo_nombre)
    # Si es metodo POST...
    if request.method == 'POST':
        miFormulario = BuzosForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid:  # Si pasó la validación de Django
            informacion = miFormulario.cleaned_data

            buzo.nombre = informacion['nombre']
            buzo.tamaño = informacion['tamaño']
            buzo.color = informacion['color']
            buzo.precio = informacion['precio']
            buzo.stock = informacion['stock']
            buzo.save()

            # Vuelvo al inicio.
            return render(request, "AppPreEntreg3/inicio.html")
    # En caso que no sea post...
    else:
        # Creo el formulario con los datos que voy a modificar
        miFormulario = BuzosForm(initial={'nombre': buzo.nombre, 'tamaño': buzo.tamaño,
                                                'color': buzo.color, 'precio': buzo.precio, 'stock': buzo.stock})
    # Voy al html que me permite editar
    return render(request, "AppPreEntreg3/editarBuzo.html", {"miFormulario": miFormulario, "buzo_nombre": buzo_nombre})

@login_required
@superadmin_required
def editarPant(request, pantalon_nombre):
    pantalon = ProdPantalon.objects.get(nombre=pantalon_nombre)
    # Si es metodo POST...
    if request.method == 'POST':
        miFormulario = PantalonesForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid:  # Si pasó la validación de Django
            informacion = miFormulario.cleaned_data

            pantalon.nombre = informacion['nombre']

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/agregarAvatar.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}
    
{% block BloqueCambiante %}
    
    <!--Aquí va lo que cambia, y lo asociado a está vista -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormulario.as_p}}
        <input class="btn btn-primary" type="submit" value="Actualizar Avatar">
    </form>

    
{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/busquedaBuzo.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}
    <form action="buscarBuzo" method="GET">

        <input type="text" name="buzo" id="buzo">

        <input type="submit" value="Buscar Buzo">
        
    </form>   
{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/busquedaPantalon.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}
    <form action="buscarPant" method="GET">

        <input type="text" name="pantalon" id="pantalon">

        <input type="submit" value="Buscar Pantalon">
        
    </form>   
{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/editarPantalon.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}
    {% if miFormulario.errors %} 
        
    <p style="color: red;"> Estan mal los datos, revisalos</p>

    {% endif %}

    <form action="" method="post">{% csrf_token %}
        <table>

            {{ miFormulario.as_table }}

        </table>
        <input type="submit", value="Enviar">
    </form>
{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/editarPerfil.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}

<style>.errorlist{color:red;} label{display:none}</style>
<main role="main">
<div class="container">
    <div class="row mt-3">
    <div class="col-md-9 mx-auto mb-5" style="text-align: center;">
        <form action="" method="post">{% csrf_token %}
        {% if miFormulario.errors %}
            <div class="alert alert-danger">
                {% for field_name, field_errors in miFormulario.errors.items %}
                    <p>{{ field_errors }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <h3 class="mb-4">Editando Perfil de "{{usuario}}"</h3>
        <p>Nombre: {{ miFormulario.first_name }}</p>
        <p>Apellido: {{ miFormulario.last_name }}</p>
        <p>Correo: {{ miFormulario.email }}</p>
        <p>Nueva Contraseña: {{ miFormulario.password1 }}</p>
        <p>Repetir Contraseña: {{ miFormulario.password2 }}</p>
        <a class="btn btn-primary" href="{% url 'AgregarAvatar' %}">Agregar Avatar</a> <br><br>
        <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
    </div>
    </div>
</div>
</main> 

{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/login.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}
    <style>.errorlist{color:red;} label{display:none}</style>
    <main role="main">
    <div class="container">
        <div class="row mt-3"> 
        <div class="col-md-9 mx-auto mb-5" style="text-align: center;">
            <form action="" method="post">{% csrf_token %}
            <h3 class="mb-4">Inicio de Sesión</h3> {% if mensaje %}<span style="color: red;">*{{ mensaje }}</span>{% endif %}
            <p>Usuario: {{ form.username }}</p>
            <p>Contraseña: {{ form.password }}</p>
            <p><input type="submit" class="btn btn-primary btn-block" value="Login"></p>
            </form>
        </div>
        </div>
    </div>
    </main>

{% endblock %}

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Tienda Ropa - Argentina</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="C:/Users/Jero/OneDrive - Acosta Daniel y Acosta Pablo S.H/Mis cosas/Cursos/Python CoderHouse/Proyecto-Final---Python-CoderHouse/Tercera Pre-Entrega/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppPreEntreg3/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand">Bienvenido</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Inicio' %}">Inicio</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Productos</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'Remeras' %}">Remeras</a></li>
                                <li><a class="dropdown-item" href="{% url 'Buzos' %}">Buzos</a></li>
                                <li><a class="dropdown-item" href="{% url 'Pantalones' %}">Pantalones</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Aboutme' %}">Sobre Mí</a></li>
                    </ul>
                </div>
                {% if request.user.is_authenticated %}
                    <ul class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hola, {{user.username}} 
                            {% with avatares=request.user.avatar_set.all %}
                            {% if avatares %}
                                {% with ultimo_avatar=avatares.last %}
                                    <img height="40px" src="{{ ultimo_avatar.imagen.url }}">
                                {% endwith %}
                            {% endif %}
                            {% endwith %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'EditarPerfil' %}">Editar Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
                        </ul>
                    </ul>
                {% else %}
                    <a class="btn btn-outline-dark" href="{% url 'Login' %}" style="margin-right: 5px;">Login</a>
                    <a class="btn btn-outline-dark" href="{% url 'Register' %}" style="margin-right: 5px;">Registrate</a>
                {% endif %}
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-4">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Tienda Ropa Argentina 2023</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Productos originales fabricados en Argentina</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">

            <!-- Esto es lo que va a cambiar-->
            {% block BloqueCambiante %}

            {% endblock %}

        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Jerónimo Gabriel Alo 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="C:/Users/Jero/OneDrive - Acosta Daniel y Acosta Pablo S.H/Mis cosas/Cursos/Python CoderHouse/Proyecto-Final---Python-CoderHouse/Tercera Pre-Entrega/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/js/scripts.js"></script>
    </body>
</html>

Proyecto Final/ProyectoPreEntreg3/AppPreEntreg3/templates/AppPreEntreg3/pantalones.html
{% extends "AppPreEntreg3/padre.html" %}

{% load static %}

{% block BloqueCambiante %}
    {% if request.user.is_authenticated and request.user.is_superuser %}
        <div class="card-footer p-2 pt-0 border-top-0 bg-transparent">
            <a class="btn btn-outline-dark mt-auto" href="{% url 'pantalonesForm' %}">Agregar Pantalones</a>
        </div>
    {% endif %}
    <div class="card-footer p-2 pt-0 border-top-0 bg-transparent">
        <a class="btn btn-outline-dark mt-auto" href="{% url 'BusquedaPantalon' %}">Buscar Pantalones</a>
    </div>
    <!--Aquí va lo que cambia, y lo asociado a está vista -->
    {% for p in pantalones %}
        <section class="py-0">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product details-->
                                    <h5 class="fw-bolder">{{p.nombre}}</h5>
                                    <h6 class="fw-semibold">Diseño: {{p.diseño}}</h6>
                                    <h6 class="fw-semibold">Tamaño: {{p.tamaño}}</h6>
                                    <h6 class="fw-semibold">Color: {{p.color}}</h6> <br>
                                    ${{p.precio}} <br>
                                    Unidades Restantes: {{p.stock}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            {% if request.user.is_authenticated and request.user.is_superuser %}
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'EditarPantalon' p.nombre %}">Editar</a></div>
                                    <br>
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'EliminarPantalon' p.nombre %}">Eliminar</a></div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endfor %}

{% endblock %}